In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pandas_profiling as pdpf

In [2]:
path= '../tableau_project.csv'
df = pd.read_csv(path, index_col= 'Unnamed: 0')

In [3]:
#df[['price', 'price_distance', 'price_duration', 'price_supplements']]

In [4]:
df.tail(5)

,journey_id,vehicle_type_id,start_type,start_at,start_lat,start_lon,end_at,end_lat,end_lon,end_state,...,price_distance,price_duration,distance,duration,source,rider_waiting_time,driver_waiting_time,price_supplements,discount,rating
3859,d850a4a8d7a244b990575a4339ee0842,21620ea5749f2e0679a8c72c7fbafb9e,asap,2017-04-17 02:26:44,19.435400,-99.148699,2017-04-17 02:52:03,19.425045,-99.170860,drop off,...,"4,134",0,"3,204",857,iPhone,650,125,0,0,6.0
3860,1688ee212d2d43bbbe5efa46b70901ab,21620ea5749f2e0679a8c72c7fbafb9e,asap,2017-04-16 23:58:41,19.425045,-99.170860,2017-04-17 00:23:32,19.432602,-99.133205,drop off,...,"5,752",0,"4,417","1,137",iPhone,330,6,0,0,6.0
3861,349a85cc381e4e0b8401c1f2bde441de,21620ea5749f2e0679a8c72c7fbafb9e,asap,2017-04-17 02:00:27,19.435400,-99.148699,2017-04-17 02:12:07,NaN,NaN,rider cancel,...,0,0,0,0,iPhone,669,NaN,0,0,6.0
3862,f7e6890738a345578e7cb3543af774e1,21620ea5749f2e0679a8c72c7fbafb9e,asap,2017-04-16 23:41:20,19.425390,-99.207499,2017-04-16 23:53:33,19.432602,-99.133205,rider cancel,...,0,0,5,252,iPhone,423,NaN,0,0,6.0
3863,67d1a13aa7b24024892ffca4585a68e2,21620ea5749f2e0679a8c72c7fbafb9e,asap,2017-04-17 02:13:29,19.435400,-99.148699,2017-04-17 02:24:35,NaN,NaN,rider cancel,...,NaN,NaN,0,0,iPhone,NaN,NaN,0,0,6.0

In [5]:
df = df.drop(['journey_id', 'start_type', 'discount', 'distance', 'duration'], axis=1)

In [6]:
null_cols = df.isnull().sum()
null_cols[null_cols > 0]

end_lat                  57
end_lon                  57
price                    20
price_distance         1052
price_duration         1052
rider_waiting_time     1131
driver_waiting_time    1179
dtype: int64

In [7]:
df.describe()

         start_lat    start_lon      end_lat      end_lon       rating
count  3864.000000  3864.000000  3807.000000  3807.000000  3864.000000
mean     19.412159   -99.195443    19.410835   -99.197221     8.289596
std       0.028146     0.040832     0.030001     0.044896     1.265744
min      19.290513   -99.288274    19.196463   -99.655665     4.000000
25%      19.405320   -99.207814    19.379486   -99.253980     8.000000
50%      19.422749   -99.175834    19.422749   -99.178435     9.000000
75%      19.426613   -99.170483    19.429759   -99.171955     9.000000
max      19.513544   -99.051114    19.517451   -99.048817    10.000000

In [8]:
report = pdpf.ProfileReport(df)
report

In [9]:
#df['end_state'=='']
df['end_state'].value_counts()

drop off         2685
rider cancel     1146
not found          20
no show            12
driver cancel       1
Name: end_state, dtype: int64

In [10]:
df_null= df[(df['end_lat'].isnull() == True) & (df['end_lon'].isnull() == True)]
df_null

,vehicle_type_id,start_at,start_lat,start_lon,end_at,end_lat,end_lon,end_state,price,price_distance,price_duration,source,rider_waiting_time,driver_waiting_time,price_supplements,rating
1,077866c3fd1a75f51ca7f8eae166ae32,2017-12-16 11:06:16,19.431567,-99.195368,2017-12-16 11:07:21,NaN,NaN,rider cancel,0,0,0,iPhone,NaN,NaN,0,9.0
152,21620ea5749f2e0679a8c72c7fbafb9e,2017-11-14 05:18:19,19.431498,-99.187064,2017-11-14 05:18:48,NaN,NaN,rider cancel,0,NaN,NaN,iPhone,NaN,NaN,0,8.0
492,21620ea5749f2e0679a8c72c7fbafb9e,2017-11-11 03:27:38,19.433270,-99.173481,2017-11-11 03:52:14,NaN,NaN,drop off,"5,588","5,088",0,web,126,133,0,10.0
750,21620ea5749f2e0679a8c72c7fbafb9e,2017-05-17 17:33:57,19.390412,-99.185959,2017-05-17 17:58:29,NaN,NaN,drop off,"6,120","6,120",0,iPhone,369,20,0,6.0
946,21620ea5749f2e0679a8c72c7fbafb9e,2017-06-09 22:34:48,19.438234,-99.201190,2017-06-09 22:34:59,NaN,NaN,rider cancel,0,NaN,NaN,iPhone,NaN,NaN,0,6.0
1162,21620ea5749f2e0679a8c72c7fbafb9e,2017-07-06 00:48:52,19.423148,-99.170471,2017-07-06 01:42:01,NaN,NaN,drop off,"8,903","8,903",0,Android,454,113,0,6.0
1164,21620ea5749f2e0679a8c72c7fbafb9e,2017-07-06 03:04:30,19.471384,-99.195378,2017-07-06 03:36:28,NaN,NaN,drop off,"7,582","7,420",162,Android,333,170,0,6.0
1193,21620ea5749f2e0679a8c72c7fbafb9e,2017-07-10 09:25:00,19.423036,-99.170413,2017-07-10 09:42:40,NaN,NaN,drop off,"13,988","9,988",0,Android,"1,797",155,0,6.0
1208,21620ea5749f2e0679a8c72c7fbafb9e,2017-07-12 12:49:09,19.423091,-99.170269,2017-07-12 13:09:35,NaN,NaN,drop off,"4,664","4,567",97,Android,336,177,0,7.0
1210,21620ea5749f2e0679a8c72c7fbafb9e,2017-07-12 13:15:49,19.423290,-99.147864,2017-07-12 14:02:06,NaN,NaN,drop off,"7,753","5,508","2,245",Android,522,798,0,7.0
1219,21620ea5749f2e0679a8c72c7fbafb9e,2017-07-13 02:50:00,19.423437,-99.175853,2017-07-13 03:14:50,NaN,NaN,drop off,"13,341","9,172",169,Android,"1,815",234,0,7.0
1253,21620ea5749f2e0679a8c72c7fbafb9e,2017-07-17 12:45:00,19.422973,-99.170483,2017-07-17 13:24:07,NaN,NaN,drop off,"17,584","13,584",0,iPhone,447,"2,512",0,8.0
1277,21620ea5749f2e0679a8c72c7fbafb9e,2017-07-19 21:03:39,19.423091,-99.170269,2017-07-19 21:53:37,NaN,NaN,drop off,"12,726","12,726",0,iPhone,293,85,0,7.0
1306,21620ea5749f2e0679a8c72c7fbafb9e,2017-07-22 14:58:16,19.423185,-99.170417,2017-07-22 15:12:20,NaN,NaN,drop off,"4,000","3,209",0,Android,208,159,0,7.0
1307,21620ea5749f2e0679a8c72c7fbafb9e,2017-07-22 15:17:44,19.423196,-99.170428,2017-07-22 15:45:46,NaN,NaN,drop off,"5,021","4,996",25,Android,618,97,0,7.0
1311,21620ea5749f2e0679a8c72c7fbafb9e,2017-07-23 00:00:01,19.435430,-99.143929,2017-07-23 00:33:09,NaN,NaN,drop off,"5,418","5,331",87,Android,432,320,0,9.0
1312,21620ea5749f2e0679a8c72c7fbafb9e,2017-07-23 14:32:55,19.423120,-99.170558,2017-07-23 15:08:17,NaN,NaN,drop off,"9,395","9,395",0,Android,"1,076",5,0,9.0
1313,21620ea5749f2e0679a8c72c7fbafb9e,2017-07-23 19:21:23,19.423091,-99.170269,2017-07-23 19:47:19,NaN,NaN,drop off,"4,000","3,228",658,Android,227,457,0,9.0
1315,21620ea5749f2e0679a8c72c7fbafb9e,2017-07-24 03:55:26,19.436356,-99.179522,2017-07-24 04:10:59,NaN,NaN,drop off,"4,000","3,257",0,Android,301,189,0,9.0
1362,21620ea5749f2e0679a8c72c7fbafb9e,2017-07-27 02:28:30,19.435530,-99.137051,2017-07-27 03:25:11,NaN,NaN,drop off,"6,341","6,341",0,Android,971,10,0,9.0
1378,21620ea5749f2e0679a8c72c7fbafb9e,2017-07-28 02:14:40,19.423091,-99.170269,2017-07-28 03:39:00,NaN,NaN,drop off,"29,583","29,299",284,Android,640,64,0,9.0
1380,21620ea5749f2e0679a8c72c7fbafb9e,2017-07-28 03:59:31,19.471507,-99.195373,2017-07-28 04:25:09,NaN,NaN,drop off,"6,654","6,654",0,Android,416,252,0,9.0
1385,21620ea5749f2e0679a8c72c7fbafb9e,2017-07-29 00:44:05,19.423170,-99.170493,2017-07-29 01:06:51,NaN,NaN,drop off,"4,000","3,524",0,Android,321,148,0,9.0
1391,21620ea5749f2e0679a8c72c7fbafb9e,2017-07-29 15:27:38,19.436588,-99.179448,2017-07-29 15:42:31,NaN,NaN,drop off,"4,000","3,169",0,Android,391,23,0,9.0
1394,21620ea5749f2e0679a8c72c7fbafb9e,2017-07-29 20:11:59,19.423107,-99.170363,2017-07-29 20:38:03,NaN,NaN,drop off,"4,000","2,663",0,Android,900,137,0,9.0
1396,21620ea5749f2e0679a8c72c7fbafb9e,2017-07-30 04:01:50,19.423107,-99.170363,2017-07-30 04:22:04,NaN,NaN,drop off,"8,064","8,064",0,Android,151,16,0,9.0
1450,21620ea5749f2e0679a8c72c7fbafb9e,2017-08-04 05:19:25,19.422880,-99.170286,2017-08-04 05:40:05,NaN,NaN,drop off,"8,391","8,294",97,Android,174,60,0,9.0
1457,21620ea5749f2e0679a8c72c7fbafb9e,2017-08-04 22:41:59,19.423054,-99.170514,2017-08-04 23:18:05,NaN,NaN,drop off,"4,662","4,641",21,Android,429,123,0,9.0
1459,21620ea5749f2e0679a8c72c7fbafb9e,2017-08-05 02:25:16,19.448256,-99.154210,2017-08-05 02:50:31,NaN,NaN,drop off,"5,226","5,226",0,Android,284,101,0,9.0
1460,21620ea5749f2e0679a8c72c7fbafb9e,2017-08-05 02:24:51,19.448310,-99.153978,2017-08-05 03:05:17,NaN,NaN,no show,"6,930",0,"6,930",Android,357,NaN,0,9.0
1462,21620ea5749f2e0679a8c72c7fbafb9e,2017-08-05 05:17:09,19.426517,-99.167412,2017-08-05 06:26:10,NaN,NaN,drop off,"31,616","31,328",288,Android,181,111,0,9.0
1464,21620ea5749f2e0679a8c72c7fbafb9e,2017-08-05 13:15:53,19.423107,-99.170363,2017-08-05 13:35:54,NaN,NaN,drop off,"4,000","3,463",0,Android,137,171,0,9.0
1466,21620ea5749f2e0679a8c72c7fbafb9e,2017-08-06 04:00:01,19.436335,-99.179362,2017-08-06 04:10:27,NaN,NaN,drop off,"4,000","2,665",0,Android,142,43,0,9.0
1471,21620ea5749f2e0679a8c72c7fbafb9e,2017-08-08 00:33:43,19.422921,-99.170406,2017-08-08 01:00:54,NaN,NaN,drop off,"7,259","7,227",32,Android,104,307,0,9.0
1538,21620ea5749f2e0679a8c72c7fbafb9e,2017-08-18 12:50:19,19.406538,-99.169710,2017-08-18 13:12:53,NaN,NaN,drop off,"4,000","2,941",0,iPhone,580,188,0,9.0
1641,21620ea5749f2e0679a8c72c7fbafb9e,2017-09-02 01:08:06,19.441434,-99.183503,2017-09-02 01:49:18,NaN,NaN,drop off,"7,857","5,005","2,852",iPhone,50,984,0,10.0
1680,21620ea5749f2e0679a8c72c7fbafb9e,2017-09-07 12:45:00,19.423091,-99.170269,2017-09-07 13:47:40,NaN,NaN,drop off,"18,674","13,641","1,033",iPhone,"2,327",946,0,8.0
1941,21620ea5749f2e0679a8c72c7fbafb9e,2017-10-03 10:45:00,19.423122,-99.170265,2017-10-03 05:47:14,NaN,NaN,rider cancel,0,NaN,NaN,Android,NaN,NaN,0,8.0
1989,21620ea5749f2e0679a8c72c7fbafb9e,2017-02-24 21:32:50,19.425520,-99.178398,2017-02-24 22:34:20,NaN,NaN,drop off,"17,511","17,511",0,Android,268,3,0,6.0
1993,21620ea5749f2e0679a8c72c7fbafb9e,2017-03-03 09:36:03,19.418180,-99.167657,2017-03-03 09:52:21,NaN,NaN,rider cancel,"4,500",0,0,iPhone,937,NaN,0,6.0
2296,21620ea5749f2e0679a8c72c7fbafb9e,2017-10-08 11:17:26,19.438811,-99.203339,2017-10-08 11:18:45,NaN,NaN,rider cancel,0,NaN,NaN,iPhone,NaN,NaN,0,6.0
2363,21620ea5749f2e0679a8c72c7fbafb9e,2017-09-21 20:55:00,19.438666,-99.180821,2017-09-21 22:02:03,NaN,NaN,drop off,"26,580","19,765","2,815",Android,327,"1,918",0,9.0
2452,21620ea5749f2e0679a8c72c7fbafb9e,2017-07-14 19:39:45,19.441327,-99.183889,2017-07-14 19:40:49,NaN,NaN,rider cancel,0,NaN,NaN,iPhone,NaN,NaN,0,6.0
2492,21620ea5749f2e0679a8c72c7fbafb9e,2017-07-08 06:55:31,19.413142,-99.172401,2017-07-08 07:15:50,NaN,NaN,drop off,"4,000","2,146",0,Android,545,218,0,6.0
2538,21620ea5749f2e0679a8c72c7fbafb9e,2017-07-01 10:17:21,19.422503,-99.170698,2017-07-01 10:43:46,NaN,NaN,drop off,"4,681","4,681",0,Android,801,176,0,6.0
3056,21620ea5749f2e0679a8c72c7fbafb9e,2017-04-04 08:03:40,19.423172,-99.174906,2017-04-04 08:28:29,NaN,NaN,drop off,"14,146","14,146",0,iPhone,194,86,0,9.0
3330,21620ea5749f2e0679a8c72c7fbafb9e,2017-02-24 14:48:23,19.427659,-99.193410,2017-02-24 15:01:37,NaN,NaN,drop off,"6,234","3,730",0,Android,218,45,0,6.0
3336,21620ea5749f2e0679a8c72c7fbafb9e,2017-02-24 18:45:57,19.440396,-99.176451,2017-02-24 19:05:32,NaN,NaN,drop off,"4,500","3,405",158,Android,124,7,0,6.0
3350,21620ea5749f2e0679a8c72c7fbafb9e,2017-02-21 14:32:43,19.424144,-99.165041,2017-02-21 15:00:29,NaN,NaN,drop off,"6,554","4,050",0,iPhone,155,3,0,6.0
3441,21620ea5749f2e0679a8c72c7fbafb9e,2017-01-26 23:29:36,19.424006,-99.164783,2017-01-27 00:13:22,NaN,NaN,drop off,"15,827","15,827",0,iPhone,382,3,0,6.0
3512,21620ea5749f2e0679a8c72c7fbafb9e,2017-02-23 14:56:34,19.427475,-99.193410,2017-02-23 15:07:29,NaN,NaN,drop off,"6,226","3,722",0,Android,229,17,0,6.0
3520,21620ea5749f2e0679a8c72c7fbafb9e,2017-02-24 00:05:16,19.438007,-99.210109,2017-02-24 00:44:08,NaN,NaN,drop off,"8,439","4,046","1,889",Android,204,306,0,6.0
3521,21620ea5749f2e0679a8c72c7fbafb9e,2017-02-24 02:24:46,19.425520,-99.178398,2017-02-24 02:39:19,NaN,NaN,drop off,"5,607","3,103",0,Android,201,58,0,6.0
3532,21620ea5749f2e0679a8c72c7fbafb9e,2017-02-25 00:45:31,19.429663,-99.195134,2017-02-25 01:52:07,NaN,NaN,drop off,"11,443","7,435","1,504",iPhone,337,98,0,6.0
3679,21620ea5749f2e0679a8c72c7fbafb9e,2017-03-16 06:20:33,19.423091,-99.170269,2017-03-16 06:39:19,NaN,NaN,drop off,"14,067","12,813",0,iPhone,108,28,"1,254",7.0
3861,21620ea5749f2e0679a8c72c7fbafb9e,2017-04-17 02:00:27,19.435400,-99.148699,2017-04-17 02:12:07,NaN,NaN,rider cancel,"4,000",0,0,iPhone,669,NaN,0,6.0
3863,21620ea5749f2e0679a8c72c7fbafb9e,2017-04-17 02:13:29,19.435400,-99.148699,2017-04-17 02:24:35,NaN,NaN,rider cancel,"4,000",NaN,NaN,iPhone,NaN,NaN,0,6.0

In [12]:
#Eliminar los recorridos sin finalizar para pintar lat, long.
df= df.drop(df_null.index)

In [13]:
df.dtypes

vehicle_type_id         object
start_at                object
start_lat              float64
start_lon              float64
end_at                  object
end_lat                float64
end_lon                float64
end_state               object
price                   object
price_distance          object
price_duration          object
source                  object
rider_waiting_time      object
driver_waiting_time     object
price_supplements       object
rating                 float64
dtype: object

In [14]:
df.query('price_distance == "0"')

,vehicle_type_id,start_at,start_lat,start_lon,end_at,end_lat,end_lon,end_state,price,price_distance,price_duration,source,rider_waiting_time,driver_waiting_time,price_supplements,rating
3,077866c3fd1a75f51ca7f8eae166ae32,2017-12-16 09:17:08,19.433119,-99.154844,2017-12-16 09:17:30,19.290148,-99.144407,rider cancel,0,0,0,iPhone,NaN,NaN,0,9.0
10,077866c3fd1a75f51ca7f8eae166ae32,2017-11-30 23:03:44,19.421545,-99.174222,2017-11-30 23:03:50,19.442719,-99.201140,rider cancel,0,0,0,iPhone,NaN,NaN,0,10.0
13,077866c3fd1a75f51ca7f8eae166ae32,2017-11-30 03:02:10,19.415241,-99.178212,2017-11-30 03:02:23,19.407004,-99.175830,rider cancel,0,0,0,Android,NaN,NaN,0,9.0
14,077866c3fd1a75f51ca7f8eae166ae32,2017-11-30 03:01:26,19.422034,-99.174665,2017-11-30 03:01:57,19.438666,-99.180821,rider cancel,0,0,0,Android,NaN,NaN,0,9.0
16,077866c3fd1a75f51ca7f8eae166ae32,2017-12-16 02:42:52,19.406538,-99.169710,2017-12-16 02:43:04,19.425151,-99.178225,rider cancel,0,0,0,iPhone,NaN,NaN,0,9.0
28,077866c3fd1a75f51ca7f8eae166ae32,2017-11-30 15:06:39,19.419962,-99.171955,2017-11-30 15:06:56,19.441434,-99.183503,rider cancel,0,0,0,iPhone,NaN,NaN,0,10.0
55,077866c3fd1a75f51ca7f8eae166ae32,2017-12-14 23:44:46,19.422016,-99.174574,2017-12-15 00:07:21,19.441414,-99.183993,rider cancel,"4,000",0,0,Android,"1,027",NaN,0,8.0
56,077866c3fd1a75f51ca7f8eae166ae32,2017-12-14 23:41:41,19.422016,-99.174574,2017-12-14 23:44:39,19.441414,-99.183993,rider cancel,0,0,0,Android,NaN,NaN,0,8.0
66,21620ea5749f2e0679a8c72c7fbafb9e,2017-11-10 11:45:00,19.407004,-99.175830,2017-11-10 11:45:47,19.429759,-99.163845,rider cancel,"10,000",0,0,Android,234,NaN,0,10.0
71,077866c3fd1a75f51ca7f8eae166ae32,2017-12-14 12:05:00,19.406134,-99.176266,2017-12-14 12:03:06,19.438666,-99.180821,rider cancel,"4,000",0,0,Android,619,NaN,0,10.0
78,077866c3fd1a75f51ca7f8eae166ae32,2017-12-08 19:20:46,19.441434,-99.183503,2017-12-08 19:21:40,19.422770,-99.174517,rider cancel,0,0,0,iPhone,NaN,NaN,0,10.0
80,077866c3fd1a75f51ca7f8eae166ae32,2017-12-08 19:07:41,19.441434,-99.183503,2017-12-08 19:20:04,19.422770,-99.174517,no show,"4,000",0,283,iPhone,344,NaN,0,10.0
81,077866c3fd1a75f51ca7f8eae166ae32,2017-12-08 19:06:06,19.441434,-99.183503,2017-12-08 19:08:23,19.422770,-99.174517,rider cancel,0,0,0,iPhone,NaN,NaN,0,10.0
82,077866c3fd1a75f51ca7f8eae166ae32,2017-12-08 19:05:11,19.441434,-99.183503,2017-12-08 19:07:15,19.422770,-99.174517,rider cancel,0,0,0,iPhone,NaN,NaN,0,10.0
88,077866c3fd1a75f51ca7f8eae166ae32,2017-12-08 14:50:39,19.419962,-99.171955,2017-12-08 14:51:00,19.441434,-99.183503,rider cancel,0,0,0,iPhone,NaN,NaN,0,10.0
89,077866c3fd1a75f51ca7f8eae166ae32,2017-12-08 14:50:03,19.419962,-99.171955,2017-12-08 14:50:11,19.441434,-99.183503,rider cancel,0,0,0,iPhone,NaN,NaN,0,10.0
90,077866c3fd1a75f51ca7f8eae166ae32,2017-12-08 14:48:46,19.419962,-99.171955,2017-12-08 14:50:18,19.441434,-99.183503,rider cancel,0,0,0,iPhone,NaN,NaN,0,10.0
91,21620ea5749f2e0679a8c72c7fbafb9e,2017-11-16 03:29:03,19.438666,-99.180821,2017-11-16 06:22:24,19.406134,-99.176266,no show,"4,000",0,"1,306",Android,"9,673",NaN,0,10.0
99,077866c3fd1a75f51ca7f8eae166ae32,2017-12-08 13:29:30,19.406538,-99.169710,2017-12-08 13:31:59,19.421960,-99.174559,rider cancel,0,0,0,iPhone,NaN,NaN,0,10.0
105,077866c3fd1a75f51ca7f8eae166ae32,2017-12-15 22:22:05,19.441358,-99.182789,2017-12-15 22:23:25,19.419962,-99.171955,rider cancel,0,0,0,iPhone,NaN,NaN,0,9.0
109,077866c3fd1a75f51ca7f8eae166ae32,2017-12-08 05:47:16,19.416204,-99.172092,2017-12-08 05:47:55,19.406438,-99.175260,rider cancel,0,0,0,Android,NaN,NaN,0,9.0
112,077866c3fd1a75f51ca7f8eae166ae32,2017-12-14 19:24:37,19.441434,-99.183503,2017-12-14 19:24:48,19.434449,-99.173414,rider cancel,0,0,0,iPhone,NaN,NaN,0,9.0
113,077866c3fd1a75f51ca7f8eae166ae32,2017-12-14 19:22:55,19.441434,-99.183503,2017-12-14 19:23:26,19.434449,-99.173414,rider cancel,0,0,0,iPhone,NaN,NaN,0,9.0
115,077866c3fd1a75f51ca7f8eae166ae32,2017-12-14 19:17:28,19.421094,-99.173639,2017-12-14 19:19:11,19.406353,-99.175294,rider cancel,0,0,0,iPhone,NaN,NaN,0,8.0
118,077866c3fd1a75f51ca7f8eae166ae32,2017-12-08 17:41:44,19.441016,-99.183586,2017-12-08 17:44:03,19.422815,-99.174865,rider cancel,0,0,0,iPhone,NaN,NaN,0,9.0
120,077866c3fd1a75f51ca7f8eae166ae32,2017-12-20 21:01:52,19.406538,-99.169710,2017-12-20 21:02:11,19.421496,-99.077809,rider cancel,0,0,0,iPhone,NaN,NaN,0,9.0
124,077866c3fd1a75f51ca7f8eae166ae32,2017-12-14 03:13:26,19.421915,-99.174626,2017-12-14 03:14:07,19.415575,-99.160113,rider cancel,0,0,0,Android,NaN,NaN,0,8.0
131,077866c3fd1a75f51ca7f8eae166ae32,2017-12-08 05:04:51,19.428070,-99.170262,2017-12-08 05:07:19,19.438666,-99.180821,rider cancel,0,0,0,Android,NaN,NaN,0,8.0
134,077866c3fd1a75f51ca7f8eae166ae32,2017-12-15 19:12:36,19.441409,-99.184154,2017-12-15 19:32:12,19.429319,-99.178289,rider cancel,0,0,0,iPhone,NaN,NaN,0,9.0
135,21620ea5749f2e0679a8c72c7fbafb9e,2017-11-14 11:45:00,19.406267,-99.176149,2017-11-14 11:31:15,19.429759,-99.163845,rider cancel,"10,000",0,0,Android,"1,587",NaN,0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2215,21620ea5749f2e0679a8c72c7fbafb9e,2017-10-12 23:59:19,19.441168,-99.183571,2017-10-13 00:54:43,19.422749,-99.174937,no show,"10,177",0,"10,177",Android,529,NaN,0,9.0
2239,21620ea5749f2e0679a8c72c7fbafb9e,2017-10-11 18:52:22,19.376909,-99.254901,2017-10-11 18:53:21,19.357106,-99.274146,rider cancel,"4,000",0,0,iPhone,26,NaN,0,10.0
2276,21620ea5749f2e0679a8c72c7fbafb9e,2017-10-10 10:40:00,19.406288,-99.176159,2017-10-10 10:52:29,19.429759,-99.163845,rider cancel,"5,285",0,"1,285",Android,"2,682",NaN,0,9.0
2307,21620ea5749f2e0679a8c72c7fbafb9e,2017-10-17 10:45:00,19.407004,-99.175830,2017-10-17 10:46:32,19.429759,-99.163845,rider cancel,"4,000",0,0,Android,"2,664",NaN,0,9.0
2335,21620ea5749f2e0679a8c72c7fbafb9e,2017-10-05 14:07:48,19.419962,-99.171955,2017-10-05 14:08:12,19.441434,-99.183503,drop off,"4,000",0,0,iPhone,3,10,0,9.0
2395,21620ea5749f2e0679a8c72c7fbafb9e,2017-09-03 07:54:59,19.395402,-99.171553,2017-09-03 08:05:46,19.415120,-99.170136,rider cancel,"4,000",0,0,iPhone,446,NaN,0,8.0
2428,21620ea5749f2e0679a8c72c7fbafb9e,2017-07-27 16:44:20,19.423103,-99.174878,2017-07-27 16:49:45,19.423103,-99.174878,rider cancel,"4,000",0,0,Android,285,NaN,0,7.0
2631,21620ea5749f2e0679a8c72c7fbafb9e,2017-06-20 04:17:58,19.423158,-99.170327,2017-06-20 04:39:46,19.499107,-99.231507,drop off,"4,000",0,"2,323",iPhone,390,857,0,6.0
2813,21620ea5749f2e0679a8c72c7fbafb9e,2017-05-23 18:50:09,19.376909,-99.254901,2017-05-23 18:59:33,19.359167,-99.270460,drop off,"4,000",0,0,iPhone,511,29,0,9.0
2829,21620ea5749f2e0679a8c72c7fbafb9e,2017-05-18 18:17:09,19.418556,-99.162560,2017-05-18 18:30:09,19.420136,-99.218120,rider cancel,"4,000",0,349,iPhone,267,NaN,0,6.0
2838,21620ea5749f2e0679a8c72c7fbafb9e,2017-10-23 10:40:00,19.406288,-99.176159,2017-10-23 10:35:50,19.429759,-99.163845,rider cancel,"4,000",0,0,Android,727,NaN,0,9.0
2852,21620ea5749f2e0679a8c72c7fbafb9e,2017-05-15 03:31:18,19.432863,-99.183147,2017-05-15 03:55:58,19.440528,-99.176656,rider cancel,"4,000",0,"1,824",iPhone,686,NaN,0,9.0
2897,21620ea5749f2e0679a8c72c7fbafb9e,2017-05-06 00:42:13,19.425521,-99.178384,2017-05-06 00:57:45,19.425735,-99.160576,rider cancel,"4,000",0,0,web,706,NaN,0,9.0
2909,21620ea5749f2e0679a8c72c7fbafb9e,2017-05-05 00:35:58,19.376909,-99.254901,2017-05-05 01:00:51,19.359167,-99.270460,rider cancel,"4,000",0,0,iPhone,548,NaN,0,9.0
2988,21620ea5749f2e0679a8c72c7fbafb9e,2017-04-11 20:21:05,19.428611,-99.161667,2017-04-11 20:36:24,19.423103,-99.174878,rider cancel,"4,000",0,0,iPhone,805,NaN,0,9.0
3014,21620ea5749f2e0679a8c72c7fbafb9e,2017-04-07 18:30:13,19.423369,-99.174653,2017-04-07 18:40:42,19.364463,-99.267453,drop off,"4,000",0,0,iPhone,617,2,0,8.0
3193,21620ea5749f2e0679a8c72c7fbafb9e,2017-10-28 08:52:54,19.424516,-99.173683,2017-10-28 08:58:52,19.436208,-99.190771,rider cancel,"4,000",0,0,Android,253,NaN,0,8.0
3224,21620ea5749f2e0679a8c72c7fbafb9e,2017-03-10 04:19:53,19.423156,-99.175119,2017-03-10 04:26:13,19.425812,-99.167486,drop off,"4,000",0,0,iPhone,70,23,0,8.0
3225,21620ea5749f2e0679a8c72c7fbafb9e,2017-03-10 05:54:23,19.376909,-99.254901,2017-03-10 06:02:09,19.359167,-99.270460,rider cancel,"4,000",0,0,iPhone,438,NaN,0,9.0
3314,21620ea5749f2e0679a8c72c7fbafb9e,2017-02-27 02:23:01,19.379486,-99.253980,2017-02-27 02:36:01,19.432315,-99.197653,drop off,"4,500",0,120,iPhone,424,328,0,9.0
3378,21620ea5749f2e0679a8c72c7fbafb9e,2017-02-18 03:12:19,19.358840,-99.278691,2017-02-18 03:21:24,19.361282,-99.273298,rider cancel,"4,500",0,0,Android,249,NaN,0,6.0
3421,21620ea5749f2e0679a8c72c7fbafb9e,2017-01-23 23:03:20,19.441321,-99.183632,2017-01-23 23:14:38,19.425458,-99.178585,no show,"4,500",0,0,Android,334,NaN,0,6.0
3541,21620ea5749f2e0679a8c72c7fbafb9e,2017-02-26 01:56:01,19.295606,-99.210565,2017-02-26 02:10:49,19.379486,-99.253980,drop off,"4,500",0,0,iPhone,696,175,0,9.0
3600,21620ea5749f2e0679a8c72c7fbafb9e,2017-03-05 03:43:04,19.439331,-99.202260,2017-03-05 04:11:13,19.422966,-99.170441,no show,"4,656",0,"4,656",iPhone,160,NaN,0,6.0
3632,21620ea5749f2e0679a8c72c7fbafb9e,2017-03-10 15:01:10,19.423135,-99.174982,2017-03-10 15:13:33,19.356000,-99.275269,rider cancel,"4,000",0,0,iPhone,717,NaN,0,8.0
3669,21620ea5749f2e0679a8c72c7fbafb9e,2017-03-15 16:43:05,19.423416,-99.174505,2017-03-15 16:54:21,19.420479,-99.094094,rider cancel,"4,000",0,0,Android,561,NaN,0,8.0
3691,21620ea5749f2e0679a8c72c7fbafb9e,2017-03-17 04:07:17,19.422966,-99.170441,2017-03-17 04:33:57,19.427108,-99.171568,no show,"4,000",0,"2,294",Android,527,NaN,0,7.0
3753,21620ea5749f2e0679a8c72c7fbafb9e,2017-03-29 15:00:05,19.359167,-99.270460,2017-03-29 15:07:18,19.376909,-99.254901,drop off,"4,000",0,0,iPhone,412,11,0,9.0
3756,21620ea5749f2e0679a8c72c7fbafb9e,2017-03-29 20:00:47,19.376909,-99.254901,2017-03-29 20:07:07,19.359167,-99.270460,drop off,"4,000",0,0,iPhone,372,1,0,9.0
3862,21620ea5749f2e0679a8c72c7fbafb9e,2017-04-16 23:41:20,19.425390,-99.207499,2017-04-16 23:53:33,19.432602,-99.133205,rider cancel,"4,000",0,0,iPhone,423,NaN,0,6.0

In [15]:
df['rider_waiting_time']=df['rider_waiting_time'].fillna('0')
df['driver_waiting_time']=df['driver_waiting_time'].fillna('0')

In [16]:
to_float_columns= ['price', 'price_distance', 'price_duration', 'price_supplements']

def convert_to_float(list_cols):
    for col in list_cols:
        df[col] = df[col].str.replace(',', '')
        df[col] = df[col].astype('float64')
        df[col] = df[col]/100

In [17]:
#todo. Los putos nan
convert_to_float(to_float_columns)

In [18]:
df.dtypes

vehicle_type_id         object
start_at                object
start_lat              float64
start_lon              float64
end_at                  object
end_lat                float64
end_lon                float64
end_state               object
price                  float64
price_distance         float64
price_duration         float64
source                  object
rider_waiting_time      object
driver_waiting_time     object
price_supplements      float64
rating                 float64
dtype: object

In [19]:
#sns.pairplot(df)

In [20]:
df_source = pd.pivot_table(df, index='source', 
                           values=['price', 'price_distance', 'price_duration','price_supplements'], aggfunc='sum')
df_source

             price  price_distance  price_duration  price_supplements
source
Android   56096.58        44107.52         2002.19             262.88
iPhone   139714.30       115978.63         5580.43            1193.27
web         644.25          576.13           28.12               0.00

In [21]:
#df_car_type = pd.pivot_table(df, index='vehicle_type_id', 
#                           values=['price', 'price_distance', 'price_duration','price_supplements'], aggfunc='sum')
#df_car_type

In [22]:
df_rating_source= pd.pivot_table(df, index= 'source', values='rating' )
df_rating_source

           rating
source
Android  7.874682
iPhone   8.497320
web      7.285714

In [23]:
df_rating_veh= pd.pivot_table(df, index= 'vehicle_type_id', values='rating' )
df_rating_veh

                                    rating
vehicle_type_id
077866c3fd1a75f51ca7f8eae166ae32  8.918552
21620ea5749f2e0679a8c72c7fbafb9e  8.261573

In [24]:
df_cancel = df[['source', 'end_state']]
df_cancel.head()

    source     end_state
0  Android      drop off
2  Android      drop off
3   iPhone  rider cancel
4   iPhone      drop off
5   iPhone      drop off

In [25]:
df_cancel[df_cancel['source']=='Android'].head()

     source     end_state
0   Android      drop off
2   Android      drop off
9   Android      drop off
12  Android      drop off
13  Android  rider cancel

In [26]:
df

,vehicle_type_id,start_at,start_lat,start_lon,end_at,end_lat,end_lon,end_state,price,price_distance,price_duration,source,rider_waiting_time,driver_waiting_time,price_supplements,rating
0,077866c3fd1a75f51ca7f8eae166ae32,2017-12-16 11:08:59,19.431363,-99.195362,2017-12-16 11:37:32,19.406438,-99.175260,drop off,58.66,52.04,0.00,Android,590,48,6.62,9.0
2,077866c3fd1a75f51ca7f8eae166ae32,2017-11-24 22:58:37,19.422052,-99.174499,2017-11-24 23:27:05,19.438666,-99.180821,drop off,40.00,35.52,0.00,Android,923,4,0.00,10.0
3,077866c3fd1a75f51ca7f8eae166ae32,2017-12-16 09:17:08,19.433119,-99.154844,2017-12-16 09:17:30,19.290148,-99.144407,rider cancel,0.00,0.00,0.00,iPhone,0,0,0.00,9.0
4,077866c3fd1a75f51ca7f8eae166ae32,2017-11-24 18:11:00,19.440996,-99.183581,2017-11-24 18:31:31,19.422815,-99.174865,drop off,40.00,29.74,0.12,iPhone,329,36,0.00,8.0
5,077866c3fd1a75f51ca7f8eae166ae32,2017-11-24 15:34:53,19.421856,-99.174361,2017-11-24 15:53:30,19.440311,-99.184146,drop off,40.00,33.46,2.90,iPhone,73,369,0.00,8.0
6,077866c3fd1a75f51ca7f8eae166ae32,2017-11-24 15:10:23,19.419962,-99.171955,2017-11-24 15:10:42,19.441434,-99.183503,rider cancel,0.00,NaN,NaN,iPhone,0,0,0.00,10.0
7,077866c3fd1a75f51ca7f8eae166ae32,2017-11-24 15:09:29,19.419962,-99.171955,2017-11-24 15:47:42,19.441434,-99.183503,drop off,64.49,43.67,20.82,iPhone,770,799,0.00,10.0
8,077866c3fd1a75f51ca7f8eae166ae32,2017-11-24 14:31:58,19.406538,-99.169710,2017-11-24 14:32:56,19.421960,-99.174559,rider cancel,0.00,NaN,NaN,iPhone,0,0,0.00,10.0
9,077866c3fd1a75f51ca7f8eae166ae32,2017-11-24 14:20:00,19.438666,-99.180821,2017-11-24 14:36:44,19.423103,-99.174878,drop off,80.63,40.63,0.00,Android,"1,655","1,039",0.00,10.0
10,077866c3fd1a75f51ca7f8eae166ae32,2017-11-30 23:03:44,19.421545,-99.174222,2017-11-30 23:03:50,19.442719,-99.201140,rider cancel,0.00,0.00,0.00,iPhone,0,0,0.00,10.0
11,077866c3fd1a75f51ca7f8eae166ae32,2017-11-30 23:02:14,19.421541,-99.174171,2017-11-30 23:35:45,19.442719,-99.201140,drop off,69.24,69.24,0.00,iPhone,729,6,0.00,10.0
12,077866c3fd1a75f51ca7f8eae166ae32,2017-11-30 03:37:44,19.422815,-99.174865,2017-11-30 04:02:56,19.406438,-99.175260,drop off,40.00,37.66,0.00,Android,633,97,0.00,9.0
13,077866c3fd1a75f51ca7f8eae166ae32,2017-11-30 03:02:10,19.415241,-99.178212,2017-11-30 03:02:23,19.407004,-99.175830,rider cancel,0.00,0.00,0.00,Android,0,0,0.00,9.0
14,077866c3fd1a75f51ca7f8eae166ae32,2017-11-30 03:01:26,19.422034,-99.174665,2017-11-30 03:01:57,19.438666,-99.180821,rider cancel,0.00,0.00,0.00,Android,0,0,0.00,9.0
15,077866c3fd1a75f51ca7f8eae166ae32,2017-11-30 01:04:57,19.441434,-99.183503,2017-11-30 02:14:25,19.439331,-99.202260,drop off,94.04,92.79,1.25,iPhone,589,158,0.00,10.0
16,077866c3fd1a75f51ca7f8eae166ae32,2017-12-16 02:42:52,19.406538,-99.169710,2017-12-16 02:43:04,19.425151,-99.178225,rider cancel,0.00,0.00,0.00,iPhone,0,0,0.00,9.0
17,077866c3fd1a75f51ca7f8eae166ae32,2017-12-16 02:25:34,19.406353,-99.175294,2017-12-16 02:51:58,19.432267,-99.154651,drop off,52.99,52.99,0.00,iPhone,477,11,0.00,8.0
18,077866c3fd1a75f51ca7f8eae166ae32,2017-11-24 04:26:15,19.422815,-99.174865,2017-11-24 04:52:20,19.406438,-99.175260,drop off,40.00,29.12,0.00,Android,576,180,0.00,9.0
19,077866c3fd1a75f51ca7f8eae166ae32,2017-11-24 04:24:26,19.422815,-99.174865,2017-11-24 04:26:09,19.406438,-99.175260,rider cancel,0.00,NaN,NaN,Android,0,0,0.00,9.0
20,077866c3fd1a75f51ca7f8eae166ae32,2017-11-24 04:13:41,19.421865,-99.174460,2017-11-24 04:15:25,19.440528,-99.176656,rider cancel,0.00,NaN,NaN,iPhone,0,0,0.00,6.0
21,077866c3fd1a75f51ca7f8eae166ae32,2017-11-30 19:03:40,19.440754,-99.183578,2017-11-30 19:39:23,19.422815,-99.174865,drop off,40.00,31.79,0.00,iPhone,873,10,0.00,8.0
22,077866c3fd1a75f51ca7f8eae166ae32,2017-11-30 19:01:29,19.441409,-99.184146,2017-11-30 19:29:52,19.427445,-99.170818,drop off,40.00,31.08,0.00,iPhone,205,262,0.00,10.0
23,077866c3fd1a75f51ca7f8eae166ae32,2017-11-30 16:40:40,19.421830,-99.174441,2017-11-30 17:08:04,19.440311,-99.184146,drop off,40.00,36.43,0.00,iPhone,856,7,0.00,8.0
24,077866c3fd1a75f51ca7f8eae166ae32,2017-11-24 02:12:27,19.438666,-99.180821,2017-11-24 02:57:54,19.406134,-99.176266,drop off,65.82,65.82,0.00,Android,"1,011",194,0.00,10.0
25,077866c3fd1a75f51ca7f8eae166ae32,2017-11-24 02:08:47,19.438666,-99.180821,2017-11-24 02:12:16,19.406134,-99.176266,rider cancel,0.00,NaN,NaN,Android,0,0,0.00,10.0
26,077866c3fd1a75f51ca7f8eae166ae32,2017-11-30 16:17:50,19.441256,-99.183574,2017-11-30 16:34:40,19.422815,-99.174865,drop off,40.00,36.44,0.00,iPhone,163,6,0.00,6.0
27,077866c3fd1a75f51ca7f8eae166ae32,2017-11-30 15:14:57,19.419962,-99.171955,2017-11-30 16:03:54,19.441434,-99.183503,drop off,54.38,40.92,13.46,iPhone,648,622,0.00,10.0
28,077866c3fd1a75f51ca7f8eae166ae32,2017-11-30 15:06:39,19.419962,-99.171955,2017-11-30 15:06:56,19.441434,-99.183503,rider cancel,0.00,0.00,0.00,iPhone,0,0,0.00,10.0
29,077866c3fd1a75f51ca7f8eae166ae32,2017-11-24 00:39:36,19.441358,-99.182789,2017-11-24 00:39:54,19.419962,-99.171955,rider cancel,0.00,NaN,NaN,iPhone,0,0,0.00,10.0
30,077866c3fd1a75f51ca7f8eae166ae32,2017-11-24 00:38:52,19.441406,-99.184136,2017-11-24 01:55:47,19.419962,-99.171955,drop off,56.10,52.38,3.72,iPhone,925,389,0.00,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3832,21620ea5749f2e0679a8c72c7fbafb9e,2017-04-07 13:44:27,19.379486,-99.253980,2017-04-07 13:45:32,19.376909,-99.254901,rider cancel,0.00,NaN,NaN,iPhone,0,0,0.00,9.0
3833,21620ea5749f2e0679a8c72c7fbafb9e,2017-04-07 14:10:14,19.423157,-99.170397,2017-04-07 14:34:12,19.441380,-99.183926,drop off,55.86,55.54,0.32,iPhone,302,99,0.00,8.0
3834,21620ea5749f2e0679a8c72c7fbafb9e,2017-04-07 19:54:21,19.364772,-99.267162,2017-04-07 19:55:23,19.498778,-99.231474,rider cancel,0.00,NaN,NaN,iPhone,0,0,0.00,8.0
3835,21620ea5749f2e0679a8c72c7fbafb9e,2017-04-07 17:31:49,19.441380,-99.183926,2017-04-07 17:57:33,19.423103,-99.174878,drop off,40.00,37.78,0.00,Android,263,4,0.00,9.0
3836,21620ea5749f2e0679a8c72c7fbafb9e,2017-04-07 20:36:05,19.376909,-99.254901,2017-04-07 20:37:26,19.379486,-99.253980,rider cancel,0.00,NaN,NaN,iPhone,0,0,0.00,9.0
3837,21620ea5749f2e0679a8c72c7fbafb9e,2017-04-07 20:39:48,19.376909,-99.254901,2017-04-07 20:42:08,19.379486,-99.253980,rider cancel,0.00,NaN,NaN,iPhone,0,0,0.00,9.0
3838,21620ea5749f2e0679a8c72c7fbafb9e,2017-04-08 00:24:25,19.419364,-99.169973,2017-04-08 00:27:47,19.433624,-99.182673,rider cancel,0.00,NaN,NaN,iPhone,0,0,0.00,8.0
3839,21620ea5749f2e0679a8c72c7fbafb9e,2017-04-07 22:54:28,19.423159,-99.174806,2017-04-07 23:37:27,19.356000,-99.275269,drop off,178.00,178.00,0.00,iPhone,498,5,0.00,9.0
3840,21620ea5749f2e0679a8c72c7fbafb9e,2017-04-08 00:45:40,19.498972,-99.231669,2017-04-08 01:36:04,19.423091,-99.170269,drop off,175.03,160.26,0.00,iPhone,524,101,14.77,8.0
3841,21620ea5749f2e0679a8c72c7fbafb9e,2017-04-08 00:19:06,19.379486,-99.253980,2017-04-08 01:48:47,19.402877,-99.098333,drop off,293.87,241.38,6.49,iPhone,676,455,46.00,9.0
3842,21620ea5749f2e0679a8c72c7fbafb9e,2017-04-08 06:23:34,19.419770,-99.165930,2017-04-08 06:53:54,19.379486,-99.253980,drop off,108.52,108.52,0.00,iPhone,142,169,0.00,9.0
3843,21620ea5749f2e0679a8c72c7fbafb9e,2017-04-08 18:40:23,19.379486,-99.253980,2017-04-08 18:40:44,19.376909,-99.254901,rider cancel,0.00,NaN,NaN,iPhone,0,0,0.00,9.0
3844,21620ea5749f2e0679a8c72c7fbafb9e,2017-04-08 16:58:27,19.423091,-99.170269,2017-04-08 17:29:20,19.432232,-99.147815,drop off,40.00,31.28,0.00,Android,326,20,0.00,9.0
3845,21620ea5749f2e0679a8c72c7fbafb9e,2017-04-10 05:01:36,19.364605,-99.259426,2017-04-10 05:04:47,19.379486,-99.253980,rider cancel,0.00,NaN,NaN,iPhone,0,0,0.00,9.0
3846,21620ea5749f2e0679a8c72c7fbafb9e,2017-04-10 12:39:46,19.379486,-99.253980,2017-04-10 12:42:33,19.376909,-99.254901,rider cancel,0.00,NaN,NaN,iPhone,0,0,0.00,9.0
3847,21620ea5749f2e0679a8c72c7fbafb9e,2017-04-10 12:50:50,19.356000,-99.275269,2017-04-10 13:35:44,19.441503,-99.183563,drop off,186.10,186.10,0.00,iPhone,503,82,0.00,9.0
3848,21620ea5749f2e0679a8c72c7fbafb9e,2017-04-10 12:42:39,19.379486,-99.253980,2017-04-10 13:07:27,19.376909,-99.254901,drop off,40.00,22.46,14.87,iPhone,456,656,0.00,9.0
3849,21620ea5749f2e0679a8c72c7fbafb9e,2017-04-10 13:17:10,19.423091,-99.170269,2017-04-10 13:37:01,19.441380,-99.183926,drop off,44.21,44.21,0.00,Android,132,54,0.00,9.0
3850,21620ea5749f2e0679a8c72c7fbafb9e,2017-04-10 18:52:51,19.376909,-99.254901,2017-04-10 19:08:08,19.379486,-99.253980,drop off,40.00,20.71,0.24,iPhone,243,305,0.00,9.0
3851,21620ea5749f2e0679a8c72c7fbafb9e,2017-04-10 20:50:10,19.379486,-99.253980,2017-04-10 21:15:01,19.376909,-99.254901,drop off,42.81,20.45,22.36,iPhone,311,836,0.00,9.0
3852,21620ea5749f2e0679a8c72c7fbafb9e,2017-04-11 00:12:11,19.441380,-99.183926,2017-04-11 00:43:13,19.423091,-99.170269,drop off,75.44,71.88,3.56,Android,285,1,0.00,9.0
3853,21620ea5749f2e0679a8c72c7fbafb9e,2017-04-11 13:12:54,19.356000,-99.275269,2017-04-11 13:50:54,19.422749,-99.174937,drop off,176.81,166.43,10.38,iPhone,69,549,0.00,9.0
3854,21620ea5749f2e0679a8c72c7fbafb9e,2017-04-11 14:38:15,19.423044,-99.174936,2017-04-11 15:03:51,19.441503,-99.183563,drop off,45.12,45.12,0.00,iPhone,473,51,0.00,9.0
3855,21620ea5749f2e0679a8c72c7fbafb9e,2017-04-11 18:04:01,19.438306,-99.202551,2017-04-11 18:06:55,19.379486,-99.253980,rider cancel,0.00,NaN,NaN,iPhone,0,0,0.00,9.0
3856,21620ea5749f2e0679a8c72c7fbafb9e,2017-04-23 16:43:22,19.425045,-99.170860,2017-04-23 17:14:27,19.355050,-99.162281,drop off,110.52,110.52,0.00,iPhone,394,69,0.00,6.0
3857,21620ea5749f2e0679a8c72c7fbafb9e,2017-05-02 15:40:18,19.425047,-99.170855,2017-05-02 17:20:42,19.260422,-99.100854,drop off,298.92,272.94,1.79,iPhone,499,46,24.19,7.0
3858,21620ea5749f2e0679a8c72c7fbafb9e,2017-04-23 16:44:57,19.425045,-99.170860,2017-04-23 17:22:23,19.355143,-99.162525,drop off,110.31,110.31,0.00,iPhone,495,45,0.00,6.0
3859,21620ea5749f2e0679a8c72c7fbafb9e,2017-04-17 02:26:44,19.435400,-99.148699,2017-04-17 02:52:03,19.425045,-99.170860,drop off,41.34,41.34,0.00,iPhone,650,125,0.00,6.0
3860,21620ea5749f2e0679a8c72c7fbafb9e,2017-04-16 23:58:41,19.425045,-99.170860,2017-04-17 00:23:32,19.432602,-99.133205,drop off,57.52,57.52,0.00,iPhone,330,6,0.00,6.0
3862,21620ea5749f2e0679a8c72c7fbafb9e,2017-04-16 23:41:20,19.425390,-99.207499,2017-04-16 23:53:33,19.432602,-99.133205,rider cancel,40.00,0.00,0.00,iPhone,423,0,0.00,6.0

In [29]:
df.to_csv('../tableau_completo.csv')